apiVersion: v1
kind: Pod
metadata:
  name: project-cards
  labels:
    app: cdc-cards
spec:
  containers:
  - name: cards-trans
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: MYENV
      valueFrom: 
        configMapKeyRef:
          name: mymap
          key: sample.conf  

