apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-dep
  labels:
    app: bnpl
spec:
  selector:
    matchLabels:
      app: cards
  replicas: 13
  template:
    metadata:
      name: hpa
      labels:
        app: cards
    spec:
      containers:
      - name: web-conatiner
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /tmp
          name: folder-vol
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "250m"     
      volumes:
      - name: folder-vol
        emptyDir: {}      
