apiVersion: v1
kind: Pod
metadata:
  name: project-cards
  labels:
    app: cdc-cards
spec:
  containers:
  - name: cards-trans
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "500Mi"
        cpu: "0.5"
      limits:
        memory: "1000Mi"
        cpu: "1"       
         
