apiVersion: v1
kind: Pod
metadata:
  name: project-cards
  labels:
    app: cdc-cards
spec:
  containers:
  - name: cards-trans
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
      -  name: secrettest
         mountPath: "/tmp/secret"  

  volumes:
  - name: secrettest
    secret:
      secretName: mysecrect
